<?php
/**
 * @file
 * Code for the CRF Requests feature.
 */

include_once 'crf_requests.features.inc';


/**
 * Implements hook_form_FORM_ID_alter().
 */
function crf_requests_form_crf_request_node_form_alter(&$form, &$form_state, $form_id) {
  $node = $form['#node'];
  if (!isset($node->nid)) {  
    $form['actions']['submit']['#value'] = t('Create & Send Info Request');
  
    // Help link
    $help_link = theme('advanced_help_topic', array(
      'module' => 'crf_requests',
      'topic' => 'request-email',
    ));
    $form['field_append_to_alert_email']['#prefix'] = $help_link . '&nbsp;' . t('Show me an Information Request email example');
  }
}


/**
 * Implements hook_node_presave().
 */
function crf_requests_node_presave($node) {
  if ($node->type == 'crf_request' && $node->is_new) {
    if (isset($node->field_crf_req_contact['und'])) {
      $cluster_contacts = crf_requests_get_cluster_contacts();    
      foreach ($cluster_contacts as $cluster_contact) {
        foreach ($node->field_crf_req_contact['und'] as $request_contact) {
          $ocha_focal_point = user_load($request_contact['target_id']);
          $params = array(
            'node' => $node,
            'cluster_contact' => $cluster_contact,
            'ocha_focal_point' => $ocha_focal_point,
          );
          drupal_mail('crf_requests', 'new_request_alert', $cluster_contact->field_contact_email['und'][0]['email'], $node->language, $params, $ocha_focal_point->mail);
        }
      }
    }
  }
}


/**
 * Implements hook_mail().
 */
function crf_requests_mail($key, &$message, $params) {
  if ($key == 'new_request_alert') {
    $node = $params['node'];
    $cluster_contact = $params['cluster_contact'];
    $ocha_focal_point = $params['ocha_focal_point'];
    
    $content_types = array();
    $content_type_names = node_type_get_names();    
    foreach ($node->field_crf_req_contents['und'] as $content_type) {
      $content_types[] = $content_type_names[$content_type['value']];
    }
    
    $append_to_email = !empty($node->field_append_to_alert_email['und']) ? $node->field_append_to_alert_email['und'][0]['value'] : '';

    $body = '<p>Dear ' . $cluster_contact->field_contact_first_name['und'][0]['value'] . ' ' . $cluster_contact->field_contact_lastname['und'][0]['value'] . ',</p>';
    $body .= '<p>OCHA (' . $ocha_focal_point->field_first_name['und'][0]['value'] . ' ' . $ocha_focal_point->field_last_name['und'][0]['value'] . ') is requesting that you provide specific information as outlined below in the Information Request ' . $node->title . '.</p>';
    $body .= '<p>' . theme('item_list', array('items' => $content_types)) . '</p>';
    $body .= '<p>' . $append_to_email . '</p>';
    $body .= '<p>Kindly provide your information online: ' . url("<front>", array("absolute" => TRUE)) . '</p>';
    $body .= '<p>Kind regards,' . '<br />';
    $body .= 'OCHA</p>';

    $message['subject'] = t('New Request for @content_types (from OCHA)', array('@content_types' => implode(',', $content_types)));
    if (isset($node->field_request_deadline['und'][0]['value'])) {
      $message['subject'] .= t(' - requested by @deadline', array('@deadline' => format_date(strtotime($node->field_request_deadline['und'][0]['value']), 'request')));
    }
    $message['body'][] = drupal_html_to_text($body);
  }
}


function crf_requests_get_cluster_contacts() {
  $contacts = array();
  
  $clusters_vocabulary = taxonomy_vocabulary_machine_name_load('clusters');
  $clusters = taxonomy_get_tree($clusters_vocabulary->vid, 0, NULL, TRUE);

  foreach ($clusters as $cluster) {
    if (!empty($cluster->field_information_focal_points)) {
      foreach ($cluster->field_information_focal_points['und'] as $information_focal_point) {
        $contacts[$information_focal_point['target_id']] = node_load($information_focal_point['target_id']);
      }
    }
  }

  return $contacts;
}


/**
 * Implements hook_block_info().
 */
function crf_requests_block_info() {
  $blocks['legend'] = array(
    'info' => t('Legend'),
  );
  $blocks['create_request'] = array(
    'info' => t('Create Request'),
  );
  $blocks['administrator'] = array(
    'info' => t('Administrator'),
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function crf_requests_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'legend':
      $legend_vars = array(
        'path' => path_to_theme() . '/images/crf_request/request-legend.png',
        'alt' => 'Legend',
        'title' => 'Legend',
        'width' => '172',
        'height' => '254',
        'attributes' => array('class' => 'request-legend'),
      );
    
      $block['subject'] = t('Legend');
      $block['content'] = theme('image', $legend_vars);
      break;
    case 'create_request':
      $items = array();
      $items[] = l('Request (Clusters)', 'node/add/crf-request');
      $items[] = l('Request (Non-Cluster)', 'node/add/non-cluster-request');
      $block['subject'] = t('Create Request');
      $block['content'] = theme('item_list', array('items' => $items));
      break;
    case 'administrator':
      $items = array();
      $items[] = l('Create Focal Point', 'node/add/contact');
      $items[] = l('Manage Content', 'admin/content');
      $items[] = l('Manage Emergencies', 'admin/structure/taxonomy/emergencies');
      $items[] = l('Manage Clusters', 'admin/structure/taxonomy/clusters');
      $block['subject'] = t('Administrator');
      $block['content'] = theme('item_list', array('items' => $items));
      break;
  }
  
  return $block;
}



